name: Foundry
version: '${project.version}'
main: net.lewmc.foundry.Foundry
api-version: 1.20
author: LewMC
description: A shared library for modern plugins.
website: https://lewmc.net
folia-supported: true
softdepend: []