env:
  MAVEN_NAME: ${{ secrets.MAVEN_NAME }}
  MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}

name: Publish project to LewMC Repo
on:
  push:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [
              {
                "id": "lewmc",
                "username": "${env.MAVEN_NAME}",
                "password": "${env.MAVEN_SECRET}"
              }
            ]
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Show generated settings.xml
        run: cat $HOME/.m2/settings.xml

      - name: Check Settings
        run: mvn help:effective-settings

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to Repository
        run: mvn deploy