name: Publish project to Maven repository
# Publish manually
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: '[{"id": "serverId", "username": "username", "password": "password"}]'
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew build publish
        env:
          MAVEN_NAME: ${{ secrets.MAVEN_NAME }} # token name
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }} # token secret (password)