name: Publish project to Maven repository
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: '[{"id": "lewmc-releases", "username": "${{ secrets.MAVEN_NAME }}", "password": "${{ secrets.MAVEN_SECRET }}"}]'
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Publish with MVN
        run: ./mvn build publish
        env:
          MAVEN_NAME: ${{ secrets.MAVEN_NAME }} # token name
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }} # token secret (password)