name: Publish project to LewMC Repo
on:
  push:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: '[{"id": "lewmc", "username": "${{ secrets.MAVEN_NAME }}", "password": "${{ secrets.MAVEN_SECRET }}"}]'
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to Repository
        run: mvn deploy